# Generated by Django 4.2.2 on 2024-07-01 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_rename_date_next_newsletter_date_send"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("set_update", "Может менять сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [("set_is_active", "Может менять активность рассылки")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="date_finish",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="date_send",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="date_start",
        ),
        migrations.AddField(
            model_name="log",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец Логов",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="datetime_finish",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата окончания рассылки",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="datetime_send",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата отправки"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="datetime_start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рассылки",
            ),
        ),
    ]
